# Generated by Django 3.0.3 on 2020-03-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_item_itemsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a season or holiday (e.g. Spring, Christmas).', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='season',
            field=models.ManyToManyField(help_text='Select all relevant seasons.', to='rentals.ItemSeason'),
        ),
    ]
