# Generated by Django 3.0.3 on 2020-03-02 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20200301_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(help_text='Select the size of the item.', null=True, on_delete=django.db.models.deletion.PROTECT, to='rentals.ItemSize'),
        ),
    ]
