# Generated by Django 3.0.3 on 2020-03-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_auto_20200301_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category (e.g. Shirts).', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory_length',
            field=models.CharField(choices=[('n', 'Not Applicable'), ('s', 'Short'), ('l', 'Long')], default='n', help_text='Choose whether item is long or short. (e.g. jeans are long, t-shirts are short, hats are Not Applicable)', max_length=1, verbose_name='Item Length'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory_weight',
            field=models.CharField(choices=[('n', 'Not Applicable'), ('h', 'Heavy'), ('l', 'Light')], default='n', help_text='Choose whether item is heavy or light. (e.g. winter jackets are heavy, t-shirts are light)', max_length=1, verbose_name='Item Weight'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(help_text='Select the category of the item.', to='rentals.ItemCategory'),
        ),
    ]
