# Generated by Django 3.0.3 on 2020-03-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_20200303_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Select the category of the item.', null=True, on_delete=django.db.models.deletion.PROTECT, to='rentals.ItemCategory'),
        ),
    ]
