# Generated by Django 3.0.3 on 2020-03-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20200303_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rentals.Parent')),
            ],
        ),
    ]
