# Generated by Django 3.0.3 on 2020-03-03 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
